#!/usr/bin/env python3
"""
Add Z.ai metadata to PDF files
"""
import sys
import os
from pypdf import PdfReader, PdfWriter

def add_metadata(input_path, output_path=None, title=None):
    """Add Z.ai metadata to PDF"""
    if output_path is None:
        output_path = input_path
    
    if title is None:
        title = os.path.splitext(os.path.basename(input_path))[0]
    
    reader = PdfReader(input_path)
    writer = PdfWriter()
    
    for page in reader.pages:
        writer.add_page(page)
    
    writer.add_metadata({
        '/Title': title,
        '/Author': 'Z.ai',
        '/Creator': 'Z.ai',
        '/Subject': 'Generated by Z.ai'
    })
    
    with open(output_path, 'wb') as f:
        writer.write(f)
    
    print(f"Metadata added to: {output_path}")

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description='Add Z.ai metadata to PDF')
    parser.add_argument('input', help='Input PDF file')
    parser.add_argument('-o', '--output', help='Output PDF file (default: overwrite input)')
    parser.add_argument('-t', '--title', help='Title metadata')
    parser.add_argument('-q', '--quiet', action='store_true', help='Quiet mode')
    
    args = parser.parse_args()
    
    if not args.quiet:
        add_metadata(args.input, args.output, args.title)
    else:
        reader = PdfReader(args.input)
        writer = PdfWriter()
        for page in reader.pages:
            writer.add_page(page)
        writer.add_metadata({
            '/Title': args.title or os.path.splitext(os.path.basename(args.input))[0],
            '/Author': 'Z.ai',
            '/Creator': 'Z.ai',
            '/Subject': 'Generated by Z.ai'
        })
        with open(args.output or args.input, 'wb') as f:
            writer.write(f)
